#40 added global error handler on APIException
looplanguage/api.pkg.looplang.org pull request #47
Opened 2021-11-04 13:24 UTC by nickonos

2021-11-04 14:05 UTC, NealGeilen approved these changes

2021-11-05 13:35 UTC, DamienKusters approved these changes

2021-11-05 13:37 UTC, DamienKusters commented
There seem to be some merge conflicts, please resolve these prior to merging.

2021-11-08 20:45 UTC, DamienKusters requested changes

2021-11-08 20:45 UTC, DamienKusters commented on lpr.Logic/Services/OrganisationService.cs
> +    public Organisation GetOrganisation(string OrgId) {
There seem to be two methods called 'GetOrganisation' in this file.

2021-11-08 20:45 UTC, DamienKusters commented on lpr.Logic/Services/OrganisationService.cs
> +    public Organisation GetOrganisation(string OrgId) {
This one can be deleted.

2021-11-09 09:04 UTC, DamienKusters approved these changes

2021-11-09 09:04 UTC, DamienKusters commented on lpr.Logic/Services/OrganisationService.cs
> +    public void AddOrganisation(string Name, string UserId) {
Maybe return something here, to confirm that AddOrganisation actually got processed.

2021-11-09 09:21 UTC, WouterPennings approved these changes

2021-11-09 09:21 UTC, merged