Lpr 28 contribution
looplanguage/api.pkg.looplang.org pull request #60
Opened 2021-11-30 10:21 UTC by NealGeilen

Added a README and pull request template
#59 needs to be accepted first

2021-11-30 15:07 UTC, nickonos approved these changes

2021-11-30 16:24 UTC, WouterPennings requested changes

2021-11-30 16:24 UTC, WouterPennings commented on README.md
> +2. Browse to the folder of the repository
Maybe something like:
2. ``cd api.pkg.looplang.org``

2021-11-30 16:24 UTC, WouterPennings commented on README.md
> +1. Clone this repository, using the following command: ``git clone https://github.com/looplanguage/api.pkg.looplang.org``
0. Open Terminal?

2021-11-30 16:24 UTC, WouterPennings commented on README.md
> +## Prerequisites
I assume this is for windows, is it the same for linux and macos?

2021-11-30 16:24 UTC, WouterPennings commented on README.md
> +3. Run the command: ``docker-compose up``
![image](https://user-images.githubusercontent.com/58933609/144086671-e1c5f97c-cc77-40c3-ad99-053ab706f2c0.png)
 I get this error....

2021-12-01 11:31 UTC, WouterPennings approved these changes

2021-12-01 11:31 UTC, merged