Feat: Account Get and Update
looplanguage/api.pkg.looplang.org pull request #62
Opened 2021-11-30 11:43 UTC by DamienKusters

Added reading Account endpoints.
Added an endpoint to Update the current logged in user.
Deletion of Accounts is not implemented for now, and will likely be its own feature.

2021-11-30 13:03 UTC, nickonos requested changes
Account should have an Identifier field where the GitHub id is stored I t should not directly store the GitHub id

2021-12-01 10:41 UTC, NealGeilen requested changes
Would like it if the current main branch is merged in this branch. 
Because of the better testing and docker building in the latest update.

2021-12-07 11:00 UTC, nickonos approved these changes

2021-12-07 11:05 UTC, NealGeilen approved these changes

2021-12-07 11:05 UTC, NealGeilen commented on lpr.Common/Models/Account.cs
> +        public AccountIdentifiers AccountIdentifiers { get; set; }
Please remove the build warnings

2021-12-07 11:42 UTC, merged